version: "3"

services:
  core:
    container_name : core-lemonde3-0
    build:
      context: core
    ports:
      - 8080:8080
  auth:
    container_name : auth-lemonde3-0
    build:
      context: auth
    ports:
      - 8081:8081
  articles:
    container_name : articles-lemonde3-0
    build:
      context: articles
    ports:
      - 8082:8082
  bookmarks:
    container_name : bookmarks-lemonde3-0
    build:
      context: bookmarks
    ports:
      - 8084:8084
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  ipfs_host:
    image: ipfs/kubo:latest
    container_name: ipfs_host
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8086:8086"
      - "127.0.0.1:5001:5001"
    volumes:
      - $ipfs_staging:/export
      - $ipfs_data:/data/ipfs
    restart: always
  ipfsservice:
    container_name : ipfsservice-lemonde3-0
    build:
      context: ipfsservice
    ports:
      - 8085:8085
