name: Azure Deployment

on:
  push:
    branches:
      - main

env:
  credentials: ${{ secrets.AZURE_PUBLISH_PROFILE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ env.credentials }}
