name: Azure Deployment

on:
  push:
    branches:
      - main

env:
  credentials: ${{ secrets.AZURE_PUBLISH_PROFILE }}
#testwith updated permissions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ env.credentials }}
