name: Azure Deployment

on:
  push:
    branches:
      - main

env: # Or as an environment variable
  credentials: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ env.credentials }}
