name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    environment: DeployBackend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y sshpass

      - name: Deploy to Azure VM
        working-directory: ${{ env.working-directory }}
        run: |
          rsync -r --progress --delete-after -e "sshpass -p '${{ secrets.AZURE_PASSWORD }}' ssh -o StrictHostKeyChecking=no" ./* ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_PUBLIC_IP }}:./

      - name: Update docker compose
        run: |
          sshpass -p "${{ secrets.AZURE_PASSWORD }}" ssh -T ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_PUBLIC_IP }} './script.sh'
