name: project build tests

on: [push, pull_request]

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo CLIENT_PORT=3000 >> .env

      - name: Build project
        run: docker-compose build > build-results

      - name: Get build results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: project-build-results
          path: ./build-results