name: web lint tests

on: [pull_request]

jobs:
  web-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: './web'

      - name: Install dependencies
        working-directory: ./web
        run: npm install

      - name: Run lint
        working-directory: ./web
        run: npm run lint > lint-results

      - name: Get lint results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: web-lint-results
          path: ./web/lint-results