name: web lint tests

on: [push, pull_request]

jobs:
  web-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint > lint-results

      - name: Get lint results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: web-lint-results
          path: ./frontend/web/lint-results