name: web build tests

on: [push, pull_request]

jobs:
  web-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        working-directory: ./frontend/web
        run: docker build . -t lemonde-web:latest > build-results

      - name: Get lint results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: web-build-results
          path: ./frontend/web/build-results